In [19]:
!ls

LCDataDictionary.xlsx
LoanStats3a.csv
LoanStats3a.csv.zip
LoanStats3b.csv
LoanStats3b.csv.zip
LoanStats3c.csv
LoanStats3c.csv.zip
LoanStats3d.csv
LoanStats3d.csv.zip
LoanStats_2016Q1.csv
LoanStats_2016Q1.csv.zip
LoanStats_2016Q2.csv
LoanStats_2016Q2.csv.zip
LoanStats_2016Q3.csv
LoanStats_2016Q3.csv.zip
LoanStats_2016Q4.csv
LoanStats_2016Q4.csv.zip
LoanStats_2017Q1.csv
LoanStats_2017Q1.csv.zip
LoanStats_2017Q2.csv
LoanStats_2017Q2.csv.zip
LoanStats_2017Q3.csv
LoanStats_2017Q3.csv.zip
LoanStats_2017Q4.csv
LoanStats_2017Q4.csv.zip
LoanStats_2018Q1.csv
LoanStats_2018Q1.csv.zip
LoanStats_2018Q2.csv
LoanStats_2018Q2.csv.zip
LoanStats_2018Q3.csv
LoanStats_2018Q3.csv.zip
LoanStats_2018Q4.csv
LoanStats_2018Q4.csv.zip
LoanStats_2019Q1.csv
LoanStats_2019Q1.csv.zip
explore_lending_club.ipynb
primaryMarketNotes_browseNotes_1-RETAIL.csv

In [2]:
import pandas as pd
pd.options.display.max_columns = 200
pd.options.display.max_rows = 200
browse = pd.read_csv('primaryMarketNotes_browseNotes_1-RETAIL.csv')
browse.shape

(58, 122)

In [3]:
browse.head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,exp_default_rate,service_fee_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,is_inc_v,accept_d,exp_d,list_d,credit_pull_d,review_status_d,review_status,url,desc,purpose,title,zip_code,addr_state,msa,acc_now_delinq,acc_open_past_24mths,bc_open_to_buy,percent_bc_gt_75,bc_util,dti,delinq_2yrs,delinq_amnt,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,mths_since_recent_inq,mths_since_recent_revol_delinq,mths_since_recent_bc,mort_acc,open_acc,pub_rec,total_bal_ex_mort,revol_bal,revol_util,total_bc_limit,total_acc,total_il_high_credit_limit,num_rev_accts,mths_since_recent_bc_dlq,initial_list_status,ils_exp_d,pub_rec_bankruptcies,num_accts_ever_120_pd,chargeoff_within_12_mths,collections_12_mths_ex_med,tax_liens,mths_since_last_major_derog,num_sats,num_tl_op_past_12m,mo_sin_rcnt_tl,tot_hi_cred_lim,tot_cur_bal,avg_cur_bal,num_bc_tl,num_actv_bc_tl,num_bc_sats,pct_tl_nvr_dlq,num_tl_90g_dpd_24m,num_tl_30dpd,num_tl_120dpd_2m,num_il_tl,mo_sin_old_il_acct,num_actv_rev_tl,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,total_rev_hi_lim,num_rev_tl_bal_gt_0,num_op_rev_tl,tot_coll_amt,effective_int_rate,application_type,disbursement_method,annual_inc_joint,dti_joint,verified_status_joint,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,inq_fi,total_cu_tl,inq_last_12m,mtg_payment,housing_payment,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog
0,152167636,186565679,22000.0,19675.0,60,11.71,5.49,0.73,486.16,B,B3,NaN,< 1 year,MORTGAGE,60000.0,Not Verified,05-24-2019 06:08:38,07-07-2019 14:00:00,06-07-2019 14:00:00,05-21-2019 09:55:17,06-07-2019 10:00:50,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Credit card refinancing,Credit card refinancing,751xx,TX,NaN,0,2,13573,40.0,58.2,14.65,0,0.0,12-20-1999 16:00:00,665,669,1,52,,3,,2,5,9,0,21005,21005.0,54.6,32500,26,0,15,,f,NaN,0,0,0,0,0,NaN,9,2,2,103750,75437,8382,8,4,5,96,0,0,0,6,154,5,226,2,38500,5,8,989,11.60,INDIVIDUAL,DIRECT_PAY,,,,2,0,0,0,73,0.0,,2,2,9285.0,54.6,0,3,2,736.00,,,,,,,,,,,,,,
1,153003150,188095322,28000.0,26725.0,36,8.19,2.16,0.86,879.88,A,A4,NaN,< 1 year,RENT,80000.0,Not Verified,06-06-2019 21:39:53,07-07-2019 18:00:00,06-07-2019 18:00:00,06-04-2019 20:38:53,06-07-2019 13:56:56,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,921xx,CA,NaN,0,1,13197,75.0,71.0,32.19,0,0.0,09-04-2005 17:00:00,715,719,0,,,16,,40,0,14,0,135969,32303.0,71.0,45500,33,140166,12,,f,NaN,0,0,0,0,0,NaN,14,0,16,185666,135969,9712,12,7,8,100,0,0,0,21,156,7,165,40,45500,7,8,0,8.18,INDIVIDUAL,CASH,,,,0,6,0,1,16,103666.0,58.7,0,0,7843.0,63.0,1,2,0,0.00,,,,,,,,,,,,,,
2,152654206,187356227,27000.0,22500.0,36,10.33,5.15,1.01,875.41,B,B1,Logistics Manager,1 year,RENT,72000.0,Source Verified,06-05-2019 07:21:02,07-06-2019 10:00:00,06-06-2019 10:00:00,05-30-2019 04:47:10,06-06-2019 06:02:41,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Credit card refinancing,Credit card refinancing,480xx,MI,NaN,0,4,5880,40.0,75.0,21.38,0,0.0,02-27-2007 16:00:00,675,679,0,25,74,8,,22,0,10,1,35499,22028.0,54.9,23500,19,24193,10,,f,NaN,1,1,0,1,0,25.0,10,2,4,64293,35499,3550,5,3,5,94,0,0,0,9,110,4,147,4,40100,4,8,151,10.22,INDIVIDUAL,DIRECT_PAY,,,,1,2,1,2,7,13471.0,55.7,1,2,11381.0,55.2,1,1,2,0.00,,,,,,,,,,,,,,
3,152209289,186627083,40000.0,15725.0,36,25.00,12.86,1.42,1590.40,D,D4,NaN,3 years,MORTGAGE,9500.0,Verified,05-27-2019 08:52:04,07-08-2019 14:00:00,06-08-2019 14:00:00,05-21-2019 15:03:03,06-08-2019 09:57:43,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,421xx,KY,NaN,0,2,922,100.0,92.6,175.22,0,0.0,11-20-2005 16:00:00,670,674,3,,,0,,21,0,9,0,70885,22427.0,85.0,12500,24,52852,11,,f,NaN,0,0,0,0,0,NaN,9,1,9,79252,70885,7876,3,3,3,100,0,0,0,13,156,7,162,21,26400,7,7,0,24.20,JOINT,CASH,109500.0,28.66,Verified,0,2,1,1,9,48458.0,91.7,0,1,6203.0,89.4,6,0,12,867.79,,60345,655,659,11-20-2005 16:00:00,4,3,16,78.0,3,15,0,0,
4,151779963,185691648,32000.0,20100.0,60,12.40,5.49,0.73,718.31,B,B4,Correction officer,10+ years,RENT,65000.0,Source Verified,06-03-2019 10:54:50,07-13-2019 10:00:00,06-13-2019 10:00:00,05-14-2019 13:50:30,06-13-2019 06:01:31,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Credit card refinancing,Credit card refinancing,112xx,NY,NaN,0,7,13541,0.0,16.9,6.09,0,0.0,02-13-2015 16:00:00,715,719,0,40,,17,40,9,0,8,0,11717,3176.0,17.1,16300,8,10000,7,,f,NaN,0,0,0,0,0,NaN,8,4,8,28600,11717,1465,4,2,4,87,0,0,0,1,8,4,51,8,18600,4,7,0,12.29,INDIVIDUAL,CASH,,,,0,1,1,1,8,8541.0,85.4,3,6,1400.0,41.0,0,2,0,0.00,,,,,,,,,,,,,,

### Read in data dictionaries

In [6]:
dictionary1 = pd.read_excel('LCDataDictionary.xlsx', sheet_name=0).set_index('LoanStatNew')

In [10]:
dictionary2 = pd.read_excel('LCDataDictionary.xlsx', sheet_name=1).set_index('BrowseNotesFile')

In [11]:
# example
dictionary2.loc['expDefaultRate']

Description    The expected default rate of the loan.
Name: expDefaultRate, dtype: object

### Data Exploration

In [12]:
browse.sort_values(by='exp_default_rate').head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,exp_default_rate,service_fee_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,is_inc_v,accept_d,exp_d,list_d,credit_pull_d,review_status_d,review_status,url,desc,purpose,title,zip_code,addr_state,msa,acc_now_delinq,acc_open_past_24mths,bc_open_to_buy,percent_bc_gt_75,bc_util,dti,delinq_2yrs,delinq_amnt,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,mths_since_recent_inq,mths_since_recent_revol_delinq,mths_since_recent_bc,mort_acc,open_acc,pub_rec,total_bal_ex_mort,revol_bal,revol_util,total_bc_limit,total_acc,total_il_high_credit_limit,num_rev_accts,mths_since_recent_bc_dlq,initial_list_status,ils_exp_d,pub_rec_bankruptcies,num_accts_ever_120_pd,chargeoff_within_12_mths,collections_12_mths_ex_med,tax_liens,mths_since_last_major_derog,num_sats,num_tl_op_past_12m,mo_sin_rcnt_tl,tot_hi_cred_lim,tot_cur_bal,avg_cur_bal,num_bc_tl,num_actv_bc_tl,num_bc_sats,pct_tl_nvr_dlq,num_tl_90g_dpd_24m,num_tl_30dpd,num_tl_120dpd_2m,num_il_tl,mo_sin_old_il_acct,num_actv_rev_tl,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,total_rev_hi_lim,num_rev_tl_bal_gt_0,num_op_rev_tl,tot_coll_amt,effective_int_rate,application_type,disbursement_method,annual_inc_joint,dti_joint,verified_status_joint,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,inq_fi,total_cu_tl,inq_last_12m,mtg_payment,housing_payment,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog
11,152966674,187986736,33325.0,16700.0,36,7.56,2.02,0.84,1037.54,A,A3,Executive Director,3 years,RENT,210000.0,Verified,06-04-2019 11:43:27,07-05-2019 10:00:00,06-05-2019 10:00:00,06-04-2019 11:36:16,06-05-2019 06:00:59,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Moving and relocation,Moving and relocation,900xx,CA,NaN,0,2,29046,62.5,67.2,38.65,0,0.0,06-03-2004 17:00:00,685,689,0,42,,,42,24,2,16,0,196983,96854.0,65.6,125900,22,138660,11,,f,NaN,0,0,0,0,0,NaN,16,1,8,329353,196983,13132,8,8,8,95,0,0,0,8,180,8,167,24,128200,8,10,72,7.56,JOINT,CASH,440000.0,26.28,Source Verified,0,5,1,1,8,37893.0,35.5,0,1,35730.0,51.2,0,0,0,0.00,,233403,695,699,04-03-1991 16:00:00,0,2,16,63.5,7,11,0,0,
28,153458677,188638496,21275.0,20525.0,36,8.19,2.16,0.86,668.55,A,A4,38B Civil Affairs Sergeant,7 years,MORTGAGE,60576.0,Not Verified,06-14-2019 13:24:16,07-14-2019 18:00:00,06-14-2019 18:00:00,06-12-2019 17:01:51,06-14-2019 13:53:30,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,283xx,NC,NaN,0,5,10389,0.0,28.4,26.43,0,0.0,11-12-2012 16:00:00,705,709,0,,,6,,2,1,9,0,67699,16874.0,32.8,14500,12,62949,8,,f,NaN,0,0,0,0,0,NaN,9,4,2,326410,276818,30758,2,2,2,91,0,0,0,3,41,6,79,2,51500,6,6,0,8.18,JOINT,CASH,91776.0,23.88,Not Verified,2,2,1,1,10,50825.0,90.0,2,3,3959.0,51.4,3,3,4,1280.28,,19463,695,699,07-12-2017 17:00:00,1,1,6,48.8,2,3,0,0,
49,153604019,189007362,25000.0,8375.0,36,8.19,2.16,0.86,785.61,A,A4,Director Program Management,< 1 year,MORTGAGE,225000.0,Not Verified,06-15-2019 09:53:28,07-15-2019 14:00:00,06-15-2019 14:00:00,06-15-2019 09:52:09,06-15-2019 09:54:27,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,180xx,PA,NaN,0,6,48385,11.1,25.8,14.26,0,0.0,01-14-1989 16:00:00,735,739,3,39,,0,39,4,2,18,0,62189,16815.0,24.5,65200,35,71631,20,39,f,NaN,0,1,0,0,0,60.0,18,5,4,365364,233296,12961,15,5,9,94,0,0,0,12,148,5,365,4,68600,5,11,146,8.18,INDIVIDUAL,CASH,,,,3,5,4,5,4,44102.0,61.6,1,1,15525.0,39.7,5,0,6,1603.13,,,,,,,,,,,,,,
45,153493944,188695713,30000.0,17050.0,36,7.02,2.16,0.86,926.59,A,A2,Intelligence Specialist,10+ years,MORTGAGE,87000.0,Source Verified,06-13-2019 05:40:54,07-13-2019 18:00:00,06-13-2019 18:00:00,06-13-2019 05:38:21,06-13-2019 13:52:07,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Other,Other,222xx,VA,NaN,0,9,46031,0.0,0.1,23.49,0,0.0,02-12-1983 16:00:00,720,724,0,36,,12,36,39,5,19,0,121842,25387.0,24.3,46100,43,89259,23,,f,NaN,0,0,0,0,0,NaN,19,6,2,344359,265172,14732,12,1,9,95,0,0,0,15,153,3,436,3,104600,3,15,0,7.01,INDIVIDUAL,CASH,,,,3,3,4,6,2,96455.0,69.2,2,2,69.0,32.4,2,14,1,1115.05,,,,,,,,,,,,,,
43,153643280,189072769,16650.0,7850.0,36,7.56,2.16,0.86,518.38,A,A3,maintenance leader,2 years,RENT,60000.0,Not Verified,06-16-2019 05:55:55,07-16-2019 10:00:00,06-16-2019 10:00:00,06-16-2019 05:33:37,06-16-2019 06:00:51,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,480xx,MI,NaN,0,2,5645,66.7,53.0,14.86,0,0.0,07-15-2006 17:00:00,705,709,0,,,17,,49,0,6,0,25433,12609.0,51.5,12000,12,16685,6,,f,NaN,0,0,0,0,0,NaN,6,0,17,41185,25433,4239,3,3,3,100,0,0,0,6,144,4,155,19,24500,4,5,0,7.55,INDIVIDUAL,CASH,,,,0,1,0,1,17,12824.0,76.9,0,1,2518.0,61.8,0,1,0,0.00,,,,,,,,,,,,,,

In [13]:
browse.sort_values(by='int_rate', ascending=False).head()

,id,member_id,loan_amnt,funded_amnt,term,int_rate,exp_default_rate,service_fee_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,is_inc_v,accept_d,exp_d,list_d,credit_pull_d,review_status_d,review_status,url,desc,purpose,title,zip_code,addr_state,msa,acc_now_delinq,acc_open_past_24mths,bc_open_to_buy,percent_bc_gt_75,bc_util,dti,delinq_2yrs,delinq_amnt,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,mths_since_recent_inq,mths_since_recent_revol_delinq,mths_since_recent_bc,mort_acc,open_acc,pub_rec,total_bal_ex_mort,revol_bal,revol_util,total_bc_limit,total_acc,total_il_high_credit_limit,num_rev_accts,mths_since_recent_bc_dlq,initial_list_status,ils_exp_d,pub_rec_bankruptcies,num_accts_ever_120_pd,chargeoff_within_12_mths,collections_12_mths_ex_med,tax_liens,mths_since_last_major_derog,num_sats,num_tl_op_past_12m,mo_sin_rcnt_tl,tot_hi_cred_lim,tot_cur_bal,avg_cur_bal,num_bc_tl,num_actv_bc_tl,num_bc_sats,pct_tl_nvr_dlq,num_tl_90g_dpd_24m,num_tl_30dpd,num_tl_120dpd_2m,num_il_tl,mo_sin_old_il_acct,num_actv_rev_tl,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,total_rev_hi_lim,num_rev_tl_bal_gt_0,num_op_rev_tl,tot_coll_amt,effective_int_rate,application_type,disbursement_method,annual_inc_joint,dti_joint,verified_status_joint,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,inq_fi,total_cu_tl,inq_last_12m,mtg_payment,housing_payment,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog
46,153501283,188730074,25000.0,11575.0,36,28.8,12.63,1.49,1044.93,D,D5,NaN,NaN,OWN,81000.0,Not Verified,06-13-2019 06:50:44,07-13-2019 10:00:00,06-13-2019 10:00:00,06-13-2019 06:49:24,06-13-2019 06:53:21,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Home improvement,Home improvement,224xx,VA,NaN,0,2,162,100.0,98.2,39.97,0,0.0,05-12-1999 17:00:00,695,699,0,,,14,,57,1,14,0,76134,48010.0,93.0,9200,26,57244,12,,f,NaN,0,0,0,0,0,NaN,14,0,14,108844,76134,5438,3,3,3,100,0,0,0,13,159,9,139,26,51600,9,9,0,28.03,INDIVIDUAL,CASH,,,,0,5,0,2,14,28124.0,49.1,0,0,4931.0,69.9,1,0,0,0.00,,,,,,,,,,,,,,
32,153379368,188520080,20000.0,13100.0,36,28.8,12.63,1.49,835.94,D,D5,Sales and Administration,10+ years,MORTGAGE,60000.0,Source Verified,06-12-2019 10:59:57,07-12-2019 18:00:00,06-12-2019 18:00:00,06-12-2019 10:50:30,06-12-2019 13:55:16,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,956xx,CA,NaN,0,3,,,,15.30,1,0.0,05-11-2001 17:00:00,670,674,2,5,,2,,,3,6,0,23847,768.0,30.7,0,15,24286,6,,f,NaN,0,1,0,0,0,78.0,6,2,2,264786,251147,50229,1,0,0,86,0,0,0,6,151,1,217,4,2500,1,3,0,28.03,INDIVIDUAL,CASH,,,,2,2,1,2,2,23079.0,95.0,1,1,0.0,89.0,0,0,2,956.00,956,,,,,,,,,,,,,
3,152209289,186627083,40000.0,15725.0,36,25.0,12.86,1.42,1590.40,D,D4,NaN,3 years,MORTGAGE,9500.0,Verified,05-27-2019 08:52:04,07-08-2019 14:00:00,06-08-2019 14:00:00,05-21-2019 15:03:03,06-08-2019 09:57:43,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,421xx,KY,NaN,0,2,922,100.0,92.6,175.22,0,0.0,11-20-2005 16:00:00,670,674,3,,,0,,21,0,9,0,70885,22427.0,85.0,12500,24,52852,11,,f,NaN,0,0,0,0,0,NaN,9,1,9,79252,70885,7876,3,3,3,100,0,0,0,13,156,7,162,21,26400,7,7,0,24.20,JOINT,CASH,109500.0,28.66,Verified,0,2,1,1,9,48458.0,91.7,0,1,6203.0,89.4,6,0,12,867.79,,60345,655,659,11-20-2005 16:00:00,4,3,16,78.0,3,15,0,0,
18,153060423,188178159,40000.0,10775.0,36,25.0,12.86,1.42,1590.40,D,D4,NaN,NaN,MORTGAGE,0.0,Not Verified,06-05-2019 16:04:30,07-08-2019 18:00:00,06-08-2019 18:00:00,06-05-2019 15:31:56,06-08-2019 15:35:22,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,640xx,MO,NaN,0,9,18036,12.5,45.8,9999.00,0,0.0,10-04-2005 17:00:00,670,674,0,,60,7,,6,0,12,1,76978,15264.0,41.7,33300,28,69958,20,,f,NaN,1,0,0,0,0,NaN,12,4,6,106558,76978,6415,12,4,8,100,0,0,0,8,130,4,164,6,36600,4,10,0,24.20,JOINT,CASH,165000.0,17.18,Not Verified,1,2,1,3,7,61714.0,80.7,3,6,8300.0,59.8,3,3,2,0.00,,40231,620,624,02-04-2006 16:00:00,2,4,10,80.4,3,17,0,0,
48,153660560,189115033,24000.0,8525.0,36,25.0,12.63,1.49,954.24,D,D4,Post Doctoral Fellow/Scientist,2 years,RENT,56000.0,Source Verified,06-16-2019 13:54:26,07-16-2019 18:00:00,06-16-2019 18:00:00,06-16-2019 13:35:03,06-16-2019 14:02:14,Approved,https://lendingclub.com/browse/loanDetail.acti...,,Debt consolidation,Debt consolidation,208xx,MD,NaN,0,6,2820,60.0,81.4,23.83,0,0.0,07-15-2005 17:00:00,675,679,0,56,,10,57,10,0,20,0,198033,13644.0,79.8,15200,25,147701,7,57,f,NaN,0,2,0,0,0,56.0,20,1,10,164801,198033,9902,6,5,5,84,0,0,0,18,167,6,113,10,17100,6,6,0,24.23,INDIVIDUAL,CASH,,,,0,14,0,3,16,184389.0,124.1,1,3,5863.0,117.9,2,1,1,0.00,,,,,,,,,,,,,,

In [16]:
browse['worst'] = -25
browse['best'] = (25 # original investment returned, plus interest...
                  + 25 * browse['term']/12 # for a given number of years
                  * (browse['int_rate'] - browse['service_fee_rate']) / 100)

In [17]:
columns = ['term', 'int_rate', 'exp_default_rate', 'service_fee_rate',
           'best', 'worst']
browse[columns].sort_values(by='best', ascending=False)

    term  int_rate  exp_default_rate  service_fee_rate     best  worst
26    60     22.50             12.91              1.12  51.7250    -25
50    60     17.97             12.91              1.12  46.0625    -25
32    36     28.80             12.63              1.49  45.4825    -25
46    36     28.80             12.63              1.49  45.4825    -25
13    60     16.40              7.33              0.83  44.4625    -25
12    60     15.57              7.33              0.83  43.4250    -25
18    36     25.00             12.86              1.42  42.6850    -25
3     36     25.00             12.86              1.42  42.6850    -25
48    36     25.00             12.63              1.49  42.6325    -25
9     36     22.50             12.86              1.42  40.8100    -25
15    36     22.50             12.63              1.49  40.7575    -25
44    60     13.08              5.48              0.75  40.4125    -25
4     60     12.40              5.49              0.73  39.5875    -25
10    36     20.00             12.86              1.42  38.9350    -25
5     36     20.00             12.86              1.42  38.9350    -25
51    36     20.00             12.63              1.49  38.8825    -25
36    36     20.00             12.63              1.49  38.8825    -25
53    36     20.00             12.63              1.49  38.8825    -25
29    36     20.00             12.63              1.49  38.8825    -25
0     60     11.71              5.49              0.73  38.7250    -25
19    60     11.02              5.48              0.75  37.8375    -25
39    36     17.97             12.86              1.42  37.4125    -25
55    36     17.97             12.63              1.49  37.3600    -25
6     60     10.33              5.49              0.73  37.0000    -25
24    60     10.33              5.48              0.75  36.9750    -25
8     36     16.40              7.19              1.15  36.4375    -25
41    36     13.90              7.19              1.15  34.5625    -25
16    60      8.19              2.22              0.60  34.4875    -25
47    36     13.08              5.14              1.03  34.0375    -25
52    36     13.08              5.14              1.03  34.0375    -25
27    36     13.08              5.14              1.03  34.0375    -25
35    36     12.40              5.14              1.03  33.5275    -25
25    36     12.40              5.14              1.03  33.5275    -25
21    36     12.40              5.14              1.03  33.5275    -25
54    36     11.71              5.14              1.03  33.0100    -25
17    36     11.71              5.14              1.03  33.0100    -25
37    36     11.71              5.14              1.03  33.0100    -25
14    36     11.02              5.15              1.01  32.5075    -25
2     36     10.33              5.15              1.01  31.9900    -25
56    36     10.33              5.15              1.01  31.9900    -25
7     36      8.81              2.16              0.86  30.9625    -25
20    36      8.81              2.16              0.86  30.9625    -25
38    36      8.81              2.16              0.86  30.9625    -25
33    36      8.81              2.16              0.86  30.9625    -25
31    36      8.81              2.16              0.86  30.9625    -25
57    36      8.81              2.16              0.86  30.9625    -25
49    36      8.19              2.16              0.86  30.4975    -25
1     36      8.19              2.16              0.86  30.4975    -25
28    36      8.19              2.16              0.86  30.4975    -25
22    36      8.19              2.16              0.86  30.4975    -25
11    36      7.56              2.02              0.84  30.0400    -25
43    36      7.56              2.16              0.86  30.0250    -25
40    36      7.56              2.16              0.86  30.0250    -25
23    36      7.56              2.16              0.86  30.0250    -25
42    36      7.02              2.16              0.86  29.6200    -25
45    36      7.02              2.16              0.86  29.6200    -25
34    36      6.46              2.16              0.86  29.2000    -25
30    36      6.46              2.16              0.86  29.2000    -25

### Use subset of loan status and loan grade from historical data

In [18]:
from glob import glob
import pandas as pd
from tqdm import tnrange, tqdm_notebook

current = pd.read_csv('primaryMarketNotes_browseNotes_1-RETAIL.csv')

files = glob('LoanStats*.csv')

def a_to_d_done(df):
    a_to_d = df['grade'].isin(['A', 'B', 'C', 'D'])
    done = df['loan_status'].isin(['Fully Paid', 'Charged Off'])
    return a_to_d & done

dfs = (pd.read_csv(file, skiprows=1, skipfooter=2, engine='python')
       .where(a_to_d_done)
       .dropna(subset=['grade', 'loan_status'])
       for file in tqdm_notebook(files))

df = pd.concat(dfs)

HBox(children=(IntProgress(value=0, max=17), HTML(value='')))

In [20]:
df.shape

(1283340, 144)

### Keep 10% of observations

In [22]:
from sklearn.model_selection import train_test_split

historical, _ = train_test_split(df.copy(), train_size=0.10, 
                             stratify=df['loan_status'])

/Users/stephensinclair/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

In [23]:
historical.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
92859,NaN,NaN,16000.0,16000.0,16000.0,60 months,11.99%,355.84,C,C1,Minitor,4 years,MORTGAGE,65000.0,Not Verified,Feb-2016,Charged Off,n,NaN,NaN,home_improvement,Home improvement,114xx,NY,4.27,0.0,Nov-1997,0.0,31.0,NaN,9.0,0.0,9425.0,36.5%,11.0,w,0.0,0.0,7106.140000,7106.14,4314.79,2791.35,0.00,0.0,0.0,Oct-2017,355.84,NaN,Aug-2018,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,218974.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,2.0,4.0,4753.0,37.0,25800.0,0.0,0.0,0.0,4.0,24330.0,16375.0,36.5,0.0,0.0,NaN,219.0,8.0,8.0,2.0,8.0,NaN,NaN,NaN,0.0,6.0,6.0,8.0,9.0,0.0,8.0,9.0,6.0,9.0,0.0,0.0,0.0,2.0,90.9,37.5,0.0,0.0,306987.0,9425.0,25800.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
219013,NaN,NaN,13000.0,13000.0,13000.0,36 months,7.90%,406.78,A,A4,NaN,NaN,MORTGAGE,55000.0,Verified,Feb-2014,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,925xx,CA,14.16,0.0,Nov-1994,0.0,NaN,NaN,15.0,0.0,19213.0,55.9%,25.0,f,0.0,0.0,14643.808894,14643.81,13000.00,1643.81,0.00,0.0,0.0,Feb-2017,406.51,NaN,Feb-2017,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,423800.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34400.0,NaN,NaN,NaN,4.0,30271.0,3301.0,72.0,0.0,0.0,106.0,230.0,1.0,1.0,5.0,78.0,NaN,11.0,NaN,0.0,4.0,13.0,4.0,5.0,1.0,14.0,19.0,13.0,15.0,0.0,0.0,0.0,4.0,100.0,50.0,0.0,0.0,447400.0,19213.0,11800.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
148211,NaN,NaN,11700.0,11700.0,11700.0,36 months,11.67%,386.77,B,B4,NaN,NaN,MORTGAGE,43000.0,Verified,Jun-2014,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,657xx,MO,14.43,0.0,Nov-1988,1.0,72.0,NaN,7.0,0.0,4515.0,91%,36.0,w,0.0,0.0,13951.331424,13951.33,11700.00,2231.99,19.34,0.0,0.0,Jun-2017,8.27,NaN,Mar-2019,0.0,70.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,62272.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4975.0,NaN,NaN,NaN,4.0,8896.0,1244.0,91.0,0.0,0.0,147.0,306.0,6.0,6.0,2.0,6.0,NaN,6.0,70.0,1.0,4.0,4.0,5.0,5.0,23.0,4.0,11.0,4.0,7.0,NaN,0.0,0.0,4.0,94.0,100.0,0.0,0.0,79590.0,6625.0,4975.0,4690.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
48536,NaN,NaN,6800.0,6800.0,6800.0,36 months,8.99%,216.21,B,B1,NaN,NaN,OWN,75000.0,Not Verified,Aug-2016,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,395xx,MS,8.78,0.0,Oct-1967,0.0,NaN,57.0,5.0,1.0,6722.0,35.8%,18.0,w,0.0,0.0,1081.050000,1081.05,838.81,242.24,0.00,0.0,0.0,Jan-2017,216.21,NaN,Jan-2017,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,13681.0,0.0,1.0,0.0,1.0,14.0,6959.0,73.0,0.0,1.0,4492.0,48.0,18800.0,0.0,1.0,0.0,2.0,2736.0,11678.0,36.5,0.0,0.0,138.0,586.0,13.0,13.0,0.0,13.0,NaN,13.0,NaN,0.0,3.0,3.0,3.0,9.0,5.0,4.0,13.0,3.0,5.0,0.0,0.0,0.0,0.0,100.0,0.0,1.0,0.0,28400.0,13681.0,18400.0,9600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
122639,NaN,NaN,6625.0,6625.0,6625.0,36 months,16.29%,233.87,C,C4,meti,2 years,MORTGAGE,33000.0,Verified,Feb-2013,Fully Paid,n,NaN,NaN,home_improvement,Home improvement,799xx,TX,26.15,0.0,Apr-2002,1.0,37.0,NaN,13.0,0.0,6465.0,54.8%,26.0,f,0.0,0.0,8419.088948,8419.09,6625.00,1794.09,0.00,0.0,0.0,Feb-2016,233.63,NaN,Nov-2017,0.0,48.0,1.0,Individual,NaN,NaN,NaN,0.0,0.0,134022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11800.0,NaN,NaN,NaN,7.0,13402.0,1097.0,63.4,0.0,0.0,94.0,132.0,13.0,10.0,1.0,37.0,37.0,0.0,37.0,4.0,1.0,5.0,3.0,11.0,4.0,9.0,21.0,5.0,13.0,0.0,0.0,0.0,1.0,76.0,50.0,0.0,0.0,146710.0,19174.0,3000.0,18003.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
historical.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,url,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,128334.000000,128334.000000,128334.000000,128334.000000,1.283340e+05,0.0,128296.000000,128334.000000,128334.000000,63113.000000,21355.000000,128334.000000,128334.000000,1.283340e+05,128334.000000,128334.0,128334.0,128334.000000,128334.000000,128334.000000,128334.000000,128334.000000,128334.000000,128334.000000,128334.000000,128333.000000,33205.000000,128334.0,2740.000000,2740.000000,128334.000000,122160.000000,1.221600e+05,55596.000000,55596.000000,55596.000000,55596.000000,54075.000000,5.559600e+04,47753.000000,55596.000000,55596.000000,55596.000000,55593.000000,1.221600e+05,55596.000000,55596.000000,55596.000000,124032.000000,122157.000000,122797.000000,122740.000000,128333.000000,128334.000000,118637.000000,122160.000000,122160.000000,122160.000000,124032.000000,122892.000000,30077.000000,111210.000000,42615.000000,122160.000000,122160.000000,122160.000000,123215.000000,122160.000000,122160.000000,122160.000000,122160.000000,122160.000000,123215.000000,117494.000000,122160.000000,122160.000000,122160.000000,122144.000000,122756.000000,128272.000000,128333.000000,1.221600e+05,1.240320e+05,124032.000000,1.221600e+05,2016.000000,2017.000000,2017.000000,2017.000000,1987.000000,2017.000000,2017.000000,2017.000000,2017.000000,679.000000,511.0,511.000000,511.0,511.000000,364.000000,511.000000,511.000000,2930.000000,2930.000000,2930.000000
mean,NaN,14026.875185,14019.374055,13999.634095,425.779286,7.704467e+04,NaN,18.055667,0.309731,0.606636,34.468445,70.668930,11.573698,0.209399,1.623286e+04,24.914894,0.0,0.0,14547.263429,14526.508046,12222.251072,2127.467699,1.472216,196.072434,33.154434,5219.651896,0.017073,43.887246,1.0,119936.333277,18.459091,0.004691,226.341634,1.419474e+05,0.997806,2.744442,0.729711,1.666541,20.325714,3.504016e+04,70.535568,1.362814,2.908698,5566.911181,57.133650,3.361330e+04,1.039841,1.591661,2.189546,4.575142,13618.081592,10789.765703,58.739506,0.008501,14.973164,126.129479,182.889350,13.407212,8.085036,1.676914,24.274046,39.634305,6.915718,35.816543,0.501465,3.633096,5.596316,4.753553,8.098576,8.504191,8.276932,14.598715,5.545162,11.617993,0.000775,0.003217,0.086444,2.098396,94.218131,43.623790,0.131050,0.050462,1.764647e+05,4.922931e+04,22272.932477,4.190982e+04,31882.140377,0.709965,1.706495,11.405553,56.237645,2.914725,13.000000,0.051066,0.073376,37.519882,3.0,117.576321,3.0,14.532290,336.212802,10253.056360,173.093973,4489.930116,47.867628,13.127986
std,NaN,8601.002527,8597.890750,8600.549481,256.966600,8.104282e+04,NaN,12.192229,0.858251,0.894783,21.916985,26.638641,5.479422,0.569552,2.341174e+04,11.962900,0.0,0.0,10013.923355,10013.620920,8711.959609,2149.536330,10.589241,831.413465,147.946633,6878.831166,0.143417,21.366190,0.0,59670.526263,7.558459,0.071886,1943.492061,1.589516e+05,1.171780,2.931287,0.964589,1.647456,25.231737,4.307721e+04,23.111074,1.523463,2.646878,5249.075202,20.952287,4.443126e+04,1.522755,2.833954,2.461717,3.123412,16624.114374,16046.540810,28.242732,0.104288,764.186646,52.214787,95.223839,16.434004,8.918948,1.996110,31.133795,22.545219,5.902739,22.424990,1.327260,2.242909,3.283055,2.973528,4.806202,7.318741,4.593389,8.157738,3.194686,5.493665,0.028425,0.059861,0.492173,1.793426,8.741309,35.822374,0.371627,0.356928,1.833774e+05,4.862079e+04,22150.541945,4.386427e+04,27987.475483,1.037809,1.891166,6.650660,26.215889,3.219279,8.494162,0.432864,0.318992,23.900713,0.0,95.142770,0.0,9.791274,282.470019,7247.405704,182.736028,3312.473747,7.045077,7.961477
min,NaN,750.000000,750.000000,0.000000,25.020000,0.000000e+00,NaN,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,2.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,19560.000000,0.210000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.700000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,3.820000,3.0,0.000000,13.650000,327.140000,0.010000,120.000000,20.000000,0.000000
25%,NaN,7500.000000,7500.000000,7475.000000,240.490000,4.600000e+04,NaN,11.590000,0.000000,0.000000,16.000000,53.000000,8.000000,0.000000,5.909250e+03,16.000000,0.0,0.0,6832.028211,6815.875000,5500.000000,731.810000,0.000000,0.000000,0.000000,385.350000,0.000000,27.000000,1.0,81000.000000,12.990000,0.000000,0.000000,2.898800e+04,0.000000,1.000000,0.000000,1.000000,7.000000,9.023000e+03,57.000000,0.000000,1.000000,2191.000000,43.000000,1.430000e+04,0.000000,0.000000,0.000000,2.000000,3067.000000,1612.000000,37.000000,0.000000,0.000000,98.000000,118.000000,4.000000,3.000000,0.000000,6.000000,21.000000,2.000000,17.000000,0.000000,2.000000,3.000000,3.000000,5.000000,3.000000,5.000000,9.000000,3.000000,8.000000,0.000000,0.000000,0.000000,1.000000,91.500000,0.000000,0.000000,0.000000,4.994650e+04,2.036450e+04,8000.000000,1.434075e+04,13520.000000,0.000000,0.000000,7.000000,37.200000,1.000000,7.000000,0.000000,0.000000,16.000000,3.0,43.585000,3.0,6.000000,125.085000,4460.155000,41.315000,1999.250000,45.000000,6.000000
50%,NaN,12000.000000,12000.000000,12000.000000,362.530000,6.500000e+04,NaN,17.320000,0.000000,0.000000,31.000000,72.000000,11.000000,0.000000,1.103300e+04,23.000000,0.0,0.0,11948.739214,11924.565000,10000.000000,1466.510000,0.000000,0.000000,0.000000,2047.560000,0.000000,44.000000,1.0,110000.000000,17.925000,0.000000,0.000000,8.083850e+04,1.000000,2.000000,0.000000,1.000000,13.000000,2.332800e+04,74.000000,1.000000,2.000000,4208.000000,58.000000,2.450000e+04,1.000000,0.000000,2.000000,4.000000,7467.000000,5075.000000,61.300000,0.000000,0.000000,130.000000,165.000000,8.000000,6.000000,1.000000,14.000000,38.000000,5.000000,33.000000,0.000000,3.000000,5.000000,4.000000,7.000000,7.000000,7.000000,13.000000,5.000000,11.000000,0.000000,0.000000,0.000000,2.000000,98.100000,40.000000,0.000000,0.000000,1.140605e+05,3.679200e+04,15600.000000,3.137050e+04,24800.500000,0.000000,1.000000,10.000000,57.500000,2.000000,11.000000,0.000000,0.000000,37.000000,3.0,92.480000,3.0,17.000000,245.385000,8677.080000,115.070000,3748.000000,45.010000,13.000000
75%,NaN,20000.000000,20000.000000,19975.000000,559.440000,9.100000e+04,NaN,23.712500,0.000000,1.000000,50.000000,90.000000,14.000000,0.000000,1.961975e+04,32.000000,0.0,0.0,20073.326667,20048.597500,17000.000000,2746.427500,0.000000,0.000000,0.000000,7858.572500,0.000000,61.000000,1.0,144000.000000,23.547500,0.000000,0.000000,2.120170e+05,2.000000,3.000000,1.000000,2.000000,23.000000,4.563625e+04,86.000000,2.000000,4.000000,7259.000000,72.000000,4.160000e+04,2.000000,2.000000,3.000000,6.000000,18948.000000,13255.000000,83.500000,0.000000,0.000000,153.000000,232.000000,16.000000,10.000000,3.000000,29.000000,58.000000,10.000000,52.000000,0.000000,5.000000,7.000000,6.000000,11.000000,11.000000,10.000000,19.000000,7.000000,14.000000,0.000000,0.000000,0.000000,3.000000,100.000000,75.000000,0.000000,0.000000,2.547805e+05,6.213175e+04,29000.000000,5.634825e+04,41487.750000,1.000000,3.000000,15.000000,77.450000,4.000000,17.000000,0.000000,0.000000,58.000000,3.0,166.050000,3.0,23.000000,474.090000,14290.120000,242.335000,6163.770000,50.000000,18.000000
max,NaN,40000.000000,40000.000000,40000.000000,1486.550000,9.000000e+06,NaN,999.000000,19.000000,8.000000,149.000000,121.000000,76.000000,19.000000,2.904836e+06,141.000000,0.0,0.0,55870.902166,55870.900000,40000.000000,20870.900000,1098.360001,31415.950000,5970.888000,41222.530000,8.000000,150.000000,1.0,660000.000000,43.420000,3.000000,262740.000000,4.447397e+06,12.000000,40.000000,14.000000,30.000000,424.000000,1.547285e+06,250.000000,26.000000,43.000000,117717.000000,154.000000,9.999999e+06,28.000000,54.000000,67.000000,50.000000,958084.000000,497445.000000,202.900000,5.000000,65000.000000,534.000000,791.000000,293.000000,194.000000,51.000000,639.000000,149.000000,25.000000,149.000000,35.000000,32.000000,52.000000,48.000000,63.000000,97.000000,71.000000,127.000000,45.000000,76.000000,2.000000,3.000000,18.000000,28.000000,100.000000,100.000000,8.000000,19.000000,9.999999e+06,2.921551e+06,760000.000000,2.000000e+06,357135.000000,6.000000,18.000000,46.000000,155.000000,28.000000,57.000000,10.000000,4.000000,125.000000,3.0,533.180000,3.0,30.000000,1599.540000,35389.370000,1247.480000,21444.000000,184.360000,36.000000

In [25]:
historical.describe(exclude='number')

,id,term,int_rate,grade,sub_grade,emp_title,emp_length,home_ownership,verification_status,issue_d,loan_status,pymnt_plan,desc,purpose,title,zip_code,addr_state,earliest_cr_line,revol_util,initial_list_status,last_pymnt_d,next_pymnt_d,last_credit_pull_d,application_type,verification_status_joint,sec_app_earliest_cr_line,hardship_flag,hardship_type,hardship_reason,hardship_status,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_loan_status,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date
count,0.0,128334,128334,128334,128334,120020,120738,128334,128334,128334,128334,128334,11206,128334,126691,128334,128334,128334,128265,128334,128129,0.0,128327,128334,2705,2017,128334,511,511,511,511,511,511,511,128334,2930,2930,2930
unique,0.0,2,395,4,20,53962,11,6,3,140,2,1,11169,14,7850,891,50,658,1104,2,133,0.0,129,2,3,397,1,1,9,2,24,27,24,5,2,61,3,70
top,NaN,36 months,10.99%,B,C1,Teacher,10+ years,MORTGAGE,Source Verified,Mar-2016,Fully Paid,n,,debt_consolidation,Debt consolidation,945xx,CA,Sep-2003,0%,w,Aug-2018,NaN,May-2019,Individual,Not Verified,Sep-2004,N,INTEREST ONLY-3 MONTHS DEFERRAL,NATURAL_DISASTER,COMPLETED,Sep-2017,Dec-2017,Sep-2017,Late (16-30 days),N,Mar-2019,COMPLETE,Jan-2019
freq,NaN,103378,3886,41625,9114,2052,42170,63729,49932,4914,105857,128334,21,73187,62438,1421,18723,888,720,77603,3566,NaN,45471,125594,1577,22,128334,511,137,364,126,87,100,249,125404,199,1349,144

In [29]:
historical.shape

(128334, 144)

In [32]:
historical.isna().mean().sort_values(ascending=False)

id                                            1.000000
member_id                                     1.000000
url                                           1.000000
next_pymnt_d                                  1.000000
orig_projected_additional_accrued_interest    0.997164
payment_plan_start_date                       0.996018
hardship_type                                 0.996018
hardship_reason                               0.996018
hardship_status                               0.996018
deferral_term                                 0.996018
hardship_start_date                           0.996018
hardship_end_date                             0.996018
hardship_amount                               0.996018
hardship_length                               0.996018
hardship_loan_status                          0.996018
hardship_payoff_balance_amount                0.996018
hardship_last_payment_amount                  0.996018
hardship_dpd                                  0.996018
sec_app_mths_since_last_major_derog           0.994709
sec_app_revol_util                            0.984517
revol_bal_joint                               0.984291
sec_app_chargeoff_within_12_mths              0.984283
sec_app_num_rev_accts                         0.984283
sec_app_open_act_il                           0.984283
sec_app_open_acc                              0.984283
sec_app_mort_acc                              0.984283
sec_app_inq_last_6mths                        0.984283
sec_app_earliest_cr_line                      0.984283
sec_app_collections_12_mths_ex_med            0.984283
verification_status_joint                     0.978922
annual_inc_joint                              0.978649
dti_joint                                     0.978649
settlement_percentage                         0.977169
settlement_term                               0.977169
settlement_status                             0.977169
settlement_amount                             0.977169
debt_settlement_flag_date                     0.977169
settlement_date                               0.977169
desc                                          0.912681
mths_since_last_record                        0.833598
mths_since_recent_bc_dlq                      0.765635
mths_since_last_major_derog                   0.741261
mths_since_recent_revol_delinq                0.667937
il_util                                       0.627901
mths_since_rcnt_il                            0.578639
all_util                                      0.566810
total_bal_il                                  0.566787
open_il_24m                                   0.566787
open_rv_12m                                   0.566787
open_rv_24m                                   0.566787
max_bal_bc                                    0.566787
total_cu_tl                                   0.566787
inq_last_12m                                  0.566787
open_il_12m                                   0.566787
open_act_il                                   0.566787
open_acc_6m                                   0.566787
inq_fi                                        0.566787
mths_since_last_delinq                        0.508213
mths_since_recent_inq                         0.133433
num_tl_120dpd_2m                              0.084467
mo_sin_old_il_acct                            0.075561
emp_title                                     0.064784
emp_length                                    0.059189
pct_tl_nvr_dlq                                0.048234
avg_cur_bal                                   0.048132
tot_cur_bal                                   0.048109
num_op_rev_tl                                 0.048109
num_tl_op_past_12m                            0.048109
num_tl_90g_dpd_24m                            0.048109
tot_coll_amt                                  0.048109
num_tl_30dpd                                  0.048109
tot_hi_cred_lim                               0.048109
num_rev_tl_bal_gt_0                           0.048109
num_rev_accts                                 0.048109
total_rev_hi_lim                              0.048109
num_il_tl                                     0.048109
total_il_high_credit_limit                    0.048109
num_bc_tl                                     0.048109
num_actv_rev_tl                               0.048109
num_actv_bc_tl                                0.048109
num_accts_ever_120_pd                         0.048109
mo_sin_rcnt_rev_tl_op                         0.048109
mo_sin_rcnt_tl                                0.048109
mo_sin_old_rev_tl_op                          0.048109
bc_util                                       0.043589
percent_bc_gt_75                              0.043465
bc_open_to_buy                                0.043145
mths_since_recent_bc                          0.042405
num_sats                                      0.039888
num_bc_sats                                   0.039888
total_bc_limit                                0.033522
total_bal_ex_mort                             0.033522
acc_open_past_24mths                          0.033522
mort_acc                                      0.033522
title                                         0.012803
last_pymnt_d                                  0.001597
revol_util                                    0.000538
pub_rec_bankruptcies                          0.000483
dti                                           0.000296
last_credit_pull_d                            0.000055
chargeoff_within_12_mths                      0.000008
collections_12_mths_ex_med                    0.000008
tax_liens                                     0.000008
loan_amnt                                     0.000000
purpose                                       0.000000
delinq_amnt                                   0.000000
pymnt_plan                                    0.000000
loan_status                                   0.000000
issue_d                                       0.000000
verification_status                           0.000000
annual_inc                                    0.000000
funded_amnt                                   0.000000
home_ownership                                0.000000
zip_code                                      0.000000
sub_grade                                     0.000000
grade                                         0.000000
installment                                   0.000000
int_rate                                      0.000000
term                                          0.000000
funded_amnt_inv                               0.000000
application_type                              0.000000
earliest_cr_line                              0.000000
addr_state                                    0.000000
delinq_2yrs                                   0.000000
hardship_flag                                 0.000000
last_pymnt_amnt                               0.000000
collection_recovery_fee                       0.000000
recoveries                                    0.000000
total_rec_late_fee                            0.000000
total_rec_int                                 0.000000
total_rec_prncp                               0.000000
total_pymnt_inv                               0.000000
total_pymnt                                   0.000000
out_prncp_inv                                 0.000000
out_prncp                                     0.000000
initial_list_status                           0.000000
total_acc                                     0.000000
revol_bal                                     0.000000
pub_rec                                       0.000000
open_acc                                      0.000000
acc_now_delinq                                0.000000
inq_last_6mths                                0.000000
policy_code                                   0.000000
debt_settlement_flag                          0.000000
dtype: float64

### Save dataframe for reuse

In [33]:
historical.to_csv('historical.csv', index=False)

### Select features

In [34]:
common_columns = set(historical.columns) & set(current.columns)
just_historical = set(historical.columns) - set(current.columns)
just_current = set(current.columns) - set(historical.columns)

In [37]:
common_columns_list = list(common_columns)

In [39]:
historical[common_columns_list].shape

(128334, 102)

In [40]:
historical_selected = historical[common_columns_list]

In [41]:
historical_selected.isna().mean().sort_values(ascending=False)

member_id                              1.000000
id                                     1.000000
url                                    1.000000
sec_app_mths_since_last_major_derog    0.994709
sec_app_revol_util                     0.984517
revol_bal_joint                        0.984291
sec_app_mort_acc                       0.984283
sec_app_open_acc                       0.984283
sec_app_earliest_cr_line               0.984283
sec_app_chargeoff_within_12_mths       0.984283
sec_app_inq_last_6mths                 0.984283
sec_app_num_rev_accts                  0.984283
sec_app_collections_12_mths_ex_med     0.984283
sec_app_open_act_il                    0.984283
annual_inc_joint                       0.978649
dti_joint                              0.978649
desc                                   0.912681
mths_since_last_record                 0.833598
mths_since_recent_bc_dlq               0.765635
mths_since_last_major_derog            0.741261
mths_since_recent_revol_delinq         0.667937
il_util                                0.627901
mths_since_rcnt_il                     0.578639
all_util                               0.566810
inq_fi                                 0.566787
open_il_12m                            0.566787
max_bal_bc                             0.566787
open_rv_24m                            0.566787
inq_last_12m                           0.566787
total_cu_tl                            0.566787
open_rv_12m                            0.566787
open_il_24m                            0.566787
open_act_il                            0.566787
open_acc_6m                            0.566787
total_bal_il                           0.566787
mths_since_last_delinq                 0.508213
mths_since_recent_inq                  0.133433
num_tl_120dpd_2m                       0.084467
mo_sin_old_il_acct                     0.075561
emp_title                              0.064784
emp_length                             0.059189
pct_tl_nvr_dlq                         0.048234
avg_cur_bal                            0.048132
num_actv_rev_tl                        0.048109
tot_coll_amt                           0.048109
num_accts_ever_120_pd                  0.048109
num_tl_90g_dpd_24m                     0.048109
num_il_tl                              0.048109
tot_hi_cred_lim                        0.048109
total_il_high_credit_limit             0.048109
num_actv_bc_tl                         0.048109
num_tl_30dpd                           0.048109
mo_sin_old_rev_tl_op                   0.048109
tot_cur_bal                            0.048109
num_rev_accts                          0.048109
mo_sin_rcnt_tl                         0.048109
num_bc_tl                              0.048109
total_rev_hi_lim                       0.048109
num_op_rev_tl                          0.048109
mo_sin_rcnt_rev_tl_op                  0.048109
num_rev_tl_bal_gt_0                    0.048109
num_tl_op_past_12m                     0.048109
bc_util                                0.043589
percent_bc_gt_75                       0.043465
bc_open_to_buy                         0.043145
mths_since_recent_bc                   0.042405
num_sats                               0.039888
num_bc_sats                            0.039888
total_bal_ex_mort                      0.033522
acc_open_past_24mths                   0.033522
mort_acc                               0.033522
total_bc_limit                         0.033522
title                                  0.012803
revol_util                             0.000538
pub_rec_bankruptcies                   0.000483
dti                                    0.000296
collections_12_mths_ex_med             0.000008
tax_liens                              0.000008
chargeoff_within_12_mths               0.000008
home_ownership                         0.000000
zip_code                               0.000000
revol_bal                              0.000000
pub_rec                                0.000000
grade                                  0.000000
sub_grade                              0.000000
loan_amnt                              0.000000
application_type                       0.000000
annual_inc                             0.000000
int_rate                               0.000000
purpose                                0.000000
initial_list_status                    0.000000
total_acc                              0.000000
installment                            0.000000
earliest_cr_line                       0.000000
delinq_2yrs                            0.000000
funded_amnt                            0.000000
inq_last_6mths                         0.000000
term                                   0.000000
open_acc                               0.000000
addr_state                             0.000000
acc_now_delinq                         0.000000
delinq_amnt                            0.000000
dtype: float64

In [42]:
print(just_historical)

{'total_pymnt_inv', 'hardship_last_payment_amount', 'settlement_percentage', 'last_pymnt_amnt', 'hardship_length', 'settlement_date', 'out_prncp_inv', 'hardship_dpd', 'hardship_loan_status', 'hardship_start_date', 'funded_amnt_inv', 'payment_plan_start_date', 'total_rec_prncp', 'settlement_term', 'next_pymnt_d', 'hardship_amount', 'policy_code', 'settlement_amount', 'hardship_status', 'deferral_term', 'settlement_status', 'hardship_payoff_balance_amount', 'orig_projected_additional_accrued_interest', 'loan_status', 'collection_recovery_fee', 'hardship_reason', 'hardship_end_date', 'last_pymnt_d', 'verification_status_joint', 'verification_status', 'hardship_flag', 'total_pymnt', 'total_rec_int', 'pymnt_plan', 'out_prncp', 'recoveries', 'issue_d', 'debt_settlement_flag', 'last_credit_pull_d', 'total_rec_late_fee', 'debt_settlement_flag_date', 'hardship_type'}